<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ImagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $images = [
        [    "id" => "1",
            "name" => "bbq_coal",
            "path" => "",
        ],
        [    "id" => "2",
            "name" => "bbq_fire",
            "path" => "",
        ],
        [    "id" => "3",
            "name" => "bbq_skewer",
            "path" => "",
        ],
        [    "id" => "4",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "5",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "6",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "7",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "8",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "9",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "10",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "11",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "12",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "13",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "14",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "15",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "16",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "17",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "18",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "19",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "20",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "21",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "22",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "23",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "24",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "25",
            "name" => "",
            "path" => "",
        ],[    "id" => "26",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "27",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "28",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "29",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "30",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "31",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "32",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "33",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "34",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "35",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "36",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "37",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "38",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "39",
            "name" => "",
            "path" => "",
        ],
        [    "id" => "40",
            "name" => "",
            "path" => "",
        ],

        ]
    }
}
